# Generated by Django 5.1.1 on 2024-10-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
